version: '2'
services:
  docker-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - docker-volume-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app-user
      MYSQL_PASSWORD: app-pass
      MYSQL_ROOT_PASSWORD: root-pass
  docker-phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    depends_on:
      - docker-mysql
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: docker-mysql
      PMA_USER: root
      PMA_PASSWORD: root-pass
  docker-app:
    build: .
    image: com-example/demo:1.0
    depends_on:
      - docker-mysql
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -Dspring.profiles.active=docker
volumes:
  docker-volume-mysql:
    driver: local
