version: '2'
services:
  dbserver:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: sboot
      MYSQL_PASSWORD: sboot
      MYSQL_ROOT_PASSWORD: root
volumes:
  mysql-db:
    driver: local
